name: C/C++ CI

on:
  push:
    branches: [ "just-test-autobuild" ]
  pull_request:
    branches: [ "just-test-autobuild" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
